version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: 'jeevakalaiselvam/steamtrackerserver'
    ports:
      - '8000:8000'
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: 'jeevakalaiselvam/steamtrackerclient'
    ports:
      - '3000:3000'
    links:
      - 'server:be'
