version: '3.8'

services:
  steamtracker-api:
    build: ./steamtracker-api
    restart: unless-stopped
    env_file: ./.env
    ports:
      - '6868:8080'
    environment:
      - CLIENT_ORIGIN=http://localhost:8888
    networks:
      - backend
      - frontend

  steamtracker-ui:
    depends_on:
      - steamtracker-api
    build:
      context: ./steamtracker-ui
      args:
        - REACT_APP_API_BASE_URL=http://127.0.0.1:6868/api/
    ports:
      - '8888:80'
    environment:
      - REACT_APP_API_BASE_URL=http://127.0.0.1:6868/api/
    networks:
      - frontend

volumes:
  db:

networks:
  backend:
  frontend:
